# -*- coding: utf-8 -*-
"""Copy of DATA_ANALYSIS_PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdLgTcoM8dK0TiJ9bgYiEft0InzSYNEd
"""





import pandas as pd

# Excel file load (file name same ga undali)
data = pd.read_excel("student_data.xlsx")

# Column names check (important)
print("Column Names:", data.columns)

# Basic Information
print("\nTotal Students:", len(data))
print("Average Marks:", data["MARKS"].mean())
print("Highest Marks:", data["MARKS"].max())
print("Lowest Marks:", data["MARKS"].min())

# Extra (Professional Output)
print("\nTop Student:")
top_student = data.loc[data["MARKS"].idxmax()]
print("Name:", top_student["NAME"])
print("Marks:", top_student["MARKS"])