# -*- coding: utf-8 -*-
"""Copy of SMART_TO_DO_LIST_PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-NrF5P83QiiDGbeNRkgRdFzQm1B-Ij6
"""

import json
import os
from datetime import datetime

FILE_NAME = "tasks.json"

class Task:
    def __init__(self, title, description, priority, deadline):
        self.title = title
        self.description = description
        self.priority = priority
        self.deadline = deadline
        self.completed = False
        self.created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def to_dict(self):
        return self.__dict__

class SmartToDoList:
    def __init__(self):
        self.tasks = []
        self.load_tasks()

    def add_task(self):
        print("\n--- Add New Task ---")
        title = input("Enter task title: ")
        description = input("Enter description: ")
        priority = input("Enter priority (High/Medium/Low): ")
        deadline = input("Enter deadline (YYYY-MM-DD): ")

        task = Task(title, description, priority, deadline)
        self.tasks.append(task)
        self.save_tasks()
        print("✅ Task added successfully!")

    def view_tasks(self):
        if not self.tasks:
            print("No tasks available.")
            return

        print("\n--- Task List ---")
        for index, task in enumerate(self.tasks):
            status = "✔ Completed" if task.completed else "❌ Pending"
            print(f"\nTask ID: {index}")
            print(f"Title: {task.title}")
            print(f"Description: {task.description}")
            print(f"Priority: {task.priority}")
            print(f"Deadline: {task.deadline}")
            print(f"Status: {status}")
            print(f"Created At: {task.created_at}")

    def mark_completed(self):
        self.view_tasks()
        try:
            task_id = int(input("\nEnter Task ID to mark as completed: "))
            self.tasks[task_id].completed = True
            self.save_tasks()
            print("✅ Task marked as completed!")
        except (IndexError, ValueError):
            print("❌ Invalid Task ID")

    def delete_task(self):
        self.view_tasks()
        try:
            task_id = int(input("\nEnter Task ID to delete: "))
            deleted = self.tasks.pop(task_id)
            self.save_tasks()
            print(f"🗑 Task '{deleted.title}' deleted successfully!")
        except (IndexError, ValueError):
            print("❌ Invalid Task ID")

    def save_tasks(self):
        with open(FILE_NAME, "w") as file:
            json.dump([task.to_dict() for task in self.tasks], file, indent=4)

    def load_tasks(self):
        if os.path.exists(FILE_NAME):
            with open(FILE_NAME, "r") as file:
                tasks_data = json.load(file)
                for task_data in tasks_data:
                    task = Task(
                        task_data["title"],
                        task_data["description"],
                        task_data["priority"],
                        task_data["deadline"]
                    )
                    task.completed = task_data["completed"]
                    task.created_at = task_data["created_at"]
                    self.tasks.append(task)

def main():
    todo = SmartToDoList()

    while True:
        print("\n====== SMART TO-DO LIST ======")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Mark Task as Completed")
        print("4. Delete Task")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            todo.add_task()
        elif choice == "2":
            todo.view_tasks()
        elif choice == "3":
            todo.mark_completed()
        elif choice == "4":
            todo.delete_task()
        elif choice == "5":
            print("👋 Exiting... Goodbye!")
            break
        else:
            print("❌ Invalid choice. Please try again.")

if __name__ == "__main__":
    main()