# -*- coding: utf-8 -*-
"""Copy of STUDENT_MANAGEMENT_SYSTEM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkBQWs9b9yhAypXeZi_97C8Ar9wZSNwj
"""

class Student:
    def __init__(self, roll_no, name, age, grade):
        self.roll_no = roll_no
        self.name = name
        self.age = age
        self.grade = grade

    def display(self):
        print(f"Roll No: {self.roll_no}")
        print(f"Name   : {self.name}")
        print(f"Age    : {self.age}")
        print(f"Grade  : {self.grade}")
        print("------------------------------")


class StudentManagementSystem:
    def __init__(self):
        self.students = []

    def add_student(self):
        roll_no = input("Enter Roll Number: ")
        name = input("Enter Name: ")
        age = input("Enter Age: ")
        grade = input("Enter Grade: ")

        student = Student(roll_no, name, age, grade)
        self.students.append(student)
        print("Student added successfully.\n")

    def view_students(self):
        if not self.students:
            print("No students found.\n")
        else:
            print("\n--- Student List ---")
            for student in self.students:
                student.display()

    def search_student(self):
        roll_no = input("Enter Roll Number to search: ")
        for student in self.students:
            if student.roll_no == roll_no:
                print("\nStudent Found:")
                student.display()
                return
        print("Student not found.\n")

    def update_student(self):
        roll_no = input("Enter Roll Number to update: ")
        for student in self.students:
            if student.roll_no == roll_no:
                student.name = input("Enter New Name: ")
                student.age = input("Enter New Age: ")
                student.grade = input("Enter New Grade: ")
                print("Student updated successfully.\n")
                return
        print("Student not found.\n")

    def delete_student(self):
        roll_no = input("Enter Roll Number to delete: ")
        for student in self.students:
            if student.roll_no == roll_no:
                self.students.remove(student)
                print("Student deleted successfully.\n")
                return
        print("Student not found.\n")


def main():
    sms = StudentManagementSystem()

    while True:
        print("===== Student Management System =====")
        print("1. Add Student")
        print("2. View Students")
        print("3. Search Student")
        print("4. Update Student")
        print("5. Delete Student")
        print("6. Exit")

        choice = input("Enter your choice (1-6): ")

        if choice == '1':
            sms.add_student()
        elif choice == '2':
            sms.view_students()
        elif choice == '3':
            sms.search_student()
        elif choice == '4':
            sms.update_student()
        elif choice == '5':
            sms.delete_student()
        elif choice == '6':
            print("Exiting program...")
            break
        else:
            print("Invalid choice. Please try again.\n")


if __name__ == "__main__":
    main()